### ISSUE TITLE
Watermarks

### ISSUE THREAD

**Issue by Androtim** [noahgsolomon/brainrot.js#11]
Is it possible to remove/replace the watermarks present during and at the end of the video when generating locally?

**Comment by Polygons1** [comment]
yes, just replace the video URL at https://github.com/noahgsolomon/brainrot.js/blob/8654759dd3d5cf7865d38fbf28133346ff7dde1c/generate/src/Composition.tsx#L368

**Comment by Androtim** [comment]
thank you!
