### ISSUE TITLE
App not working after providing all the needed api kets

### ISSUE THREAD

**Issue by raksonraks** [noahgsolomon/brainrot.js#19]
After installing the app and install the requirements needed for it to function,I ran into an issue that involves the groq api key.
I tried putting it in quotes removing quotes putting a space between the equals sign and the api key.
Also i am running the transcribe python file.
The Error:
![image](https://github.com/user-attachments/assets/6b1b3671-622d-4ea5-b11c-b397c0677bbf)

**Comment by noahgsolomon** [comment]
in .env set GROQ_API_KEY to be your groq api key. Make sure you're running 'node build.mjs' (bun has some problems with this), and let me know if you still get an error. This seems like an easy fix

**Comment by raksonraks** [comment]
so i did set my api keys i the .env.example file and i ran the 'node localBuild.mjs' file but could it be that the problem is caused by me running this program on a rdp

**Comment by raksonraks** [comment]
Turns out I just forgot to activate the virtual enviorement,I just forgot to activate the venv bcs i am running this on a vm.
But i ran into a new error:
![image](https://github.com/user-attachments/assets/35936d8a-04f3-4cd9-9a3f-eeafc1a568e5)
So any thoughts on this one.
xD.

**Comment by noahgsolomon** [comment]
And you have made the .env in generate/ and ran npm install inside generate/? 

Having a .env in root or running npm install in root will give these errors

**Comment by raksonraks** [comment]
I am not running the tool on a linux based system or a wsl i am just running it on a plain azure rdp.
I prodvided all the needed data for the tool to function but it still give me the same error.
Also, is this tool made for a windows system or a linux based system?

**Comment by noahgsolomon** [comment]
It should be working on both, and I know people who have gotten it working on windows and I've used it personally on mac and linux. 

https://www.youtube.com/watch?v=-Ff0xG1eNjw

have u watched this video and followed it step by step?

**Comment by raksonraks** [comment]
First of,I just wanted to say thanks because u made me aware that there is a tutorial video,i just watched it and i applied everything on my actual system.
But i ran into a new issue and that is the program is demanding a .mp3 file.
Here is a screanshot of what the issue seems to be:
![image](https://github.com/user-attachments/assets/70883034-b5c0-4c49-8b2d-646f6f2b59d2)

Thanks.

**Comment by noahgsolomon** [comment]
Did you set the eleven labs api key and the google custom search engine api key?

**Comment by raksonraks** [comment]
Yes,I did set the eleven labs api key but i didint set the google one bcs it wasent needed

**Comment by noahgsolomon** [comment]
You have the generate/public/voice and generate/public/srt folders created, right?

**Comment by raksonraks** [comment]
Yes i do
