### ISSUE TITLE
FPS output does not allow uploading to tiktok

### ISSUE THREAD

**Issue by shagg-e** [noahgsolomon/brainrot.js#2]
It seems the videos are being output at 60.0x fps, which is just barely above Tiktok's limit of 60fps. I've tried a few videos and they're all just barely too much FPS. Works fine for Youtube though.

**Comment by noahgsolomon** [comment]
interesting... is this on brainrotjs.com or when you generate a video locally?

**Comment by shagg-e** [comment]
On the website - interestingly enough I just did some additional testing. I
use Simplified to post to all platforms I post on from one interface, and
Simplified complained that it was too high framerate for Tiktok. Uploading
directly on Tiktok though worked fine. My best guess is that Tiktok native
allows a little wiggleroom, but Simplified does not and is very strict?

Rendering at 59fps could solve this I bet. Will there be any controls for
things like framerate, video length, etc? Youtube does not consider them
shorts unfortunately from my few test uploads just now, since they're all
1:00-1:01 long.

**Comment by noahgsolomon** [comment]
yeah look at generate/src/Root.tsx and generate/src/Composition.tsx

they're in the code defaulted to 20 but can be changed to anything
