### ISSUE TITLE
Error when trying to run transcribe.py

### ISSUE THREAD

**Issue by 5viki** [noahgsolomon/brainrot.js#20]
Hello, the first time I tried running brainrot.js locally everything worked except my missing openAI tokens, so I returned the next day only to get greeted with this peculiar missing modules error when I wanted to run transcribe.py:
![Screenshot 2024-08-08 114645](https://github.com/user-attachments/assets/207a8483-a660-47c6-b5c3-0fcb12510707)
I haven't made any changes overnight or anything, ran pip install again and nothing was missing, tried switching to a different python version, followed the instructions again, all to no avail. As this same command worked perfectly fine just a day before I am perplexed. Any help would be greatly appreciated! :)

**Comment by noahgsolomon** [comment]
I'll try to help. So you ran "pip install -r requirements.txt" inside the generate/ folder? And you created a virtual environment before doing that and activated it? The venv folder should be in generate/venv/

Is this all correct?

**Comment by 5viki** [comment]
yes, that is exactly what I've done. 
![Screenshot 2024-08-08 140627](https://github.com/user-attachments/assets/af486188-3461-4e83-9681-cd774e96a406)
![Screenshot 2024-08-08 140608](https://github.com/user-attachments/assets/37e9dcfd-2528-4fc4-a86b-f97c33188b9c)

**Comment by noahgsolomon** [comment]
weird. I've never had this complaint so I imagine it works fine typically on windows. Try using python in place of python3, not really sure. This is a python configuration issue more than a brainrot config issue and I'm no python expert haha

**Comment by eric8he** [comment]
See: https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969

Seems to be a Windows issue solvable by installing the latest Windows C++ Redistributable.
