### ISSUE TITLE
Paid cloud version doesn't work (error on render step)

### ISSUE THREAD

**Issue by ivryb** [noahgsolomon/brainrot.js#21]
Hi! I tried to generate a video on the website, and it just errors at the rendering step.
I tried it two times, and it errored both times.

<img width="477" alt="image" src="https://github.com/user-attachments/assets/53789d26-4678-4503-9463-c9d60f08febd">

**Comment by noahgsolomon** [comment]
Super sorry. Try again it should work now

**Comment by ivryb** [comment]
Yep, it works! Thanks)
