### ISSUE TITLE
Transcription Issue Relating to .SRT file missing(likely not Generated?)

### ISSUE THREAD

**Issue by Daraido** [noahgsolomon/brainrot.js#5]
After running node localBuild.mjs, my machine gets to the transcription, or subtitle part, after consolidating the audio files, but when it gets to that part, it has an error I can't trace back and I dont know how to fix, any suggestions?(BTW don't really know how to code so be specific please)
error message i receive

Finished concatenating audio files!
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open 'public/srt/BARACK_OBAMA-0.srt'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'public/srt/BARACK_OBAMA-0.srt'
}

**Comment by noahgsolomon** [comment]
are you running the python transcribe.py? That should be running on port 5000

**Comment by Daraido** [comment]
yes, and it is running in a virtual environment as well

**Comment by Daraido** [comment]
i also tried installing the ffmpeg files myself too, because i thought that might have been the problem, maybe i did that wrong?

**Comment by noahgsolomon** [comment]
Do you have the public/srt directory? The problems seems to be that the srt files aren't being wrote. Also, after every generation u should delete everything in public/voice and public/srt, and remove the src/tmp/context.tsx file if they're still there.

It'd be worth looking at the terminal you run python3 transcribe.py in to see if it is getting errors

**Comment by Daraido** [comment]
okay, creating a public/srt file fixed it, appreciate your help.

**Comment by noahgsolomon** [comment]
lfg! Good stuff. So you're able to generate locally now?

**Comment by Daraido** [comment]
yep, and its working great, thanks so much
