### ISSUE TITLE
Presidents voices not working

### ISSUE THREAD

**Issue by Daraido** [noahgsolomon/brainrot.js#6]
President voices(Donald, Joe, and Obama) arent working with eleven labs, any solutions? alternatives? workarounds?

**Comment by Daraido** [comment]
Says they have the access to president voices being blocked because of the upcoming elections...

**Comment by noahgsolomon** [comment]
yep... that's common, eleven labs doesn't like making voices of political ppl. I'm moving over to neets ai instead of eleven labs within the next week so if u hang tight it will be implemented in this codebase.

**Comment by Daraido** [comment]
okay awesome, sounds good
