### ISSUE TITLE
Port error

### ISSUE THREAD

**Issue by Androtim** [noahgsolomon/brainrot.js#9]
After running `node localBuild.mjs`, I get the following error:

`file:///home/androtim/brainrot.js/generate/node_modules/mysql2/promise.js:374`
`    const localErr = new Error();`
`                     ^`
`Error: connect ECONNREFUSED 127.0.0.1:3306`
`    at PromisePool.execute (/home/androtim/brainrot.js/generate/node_modules/mysql2/promise.js:374:22)`
`    at query (file:///home/androtim/brainrot.js/generate/dbClient.mjs:21:31)`
`    at transcribeFunction (file:///home/androtim/brainrot.js/generate/transcribe.mjs:98:9)`
`    at async main (file:///home/androtim/brainrot.js/generate/localBuild.mjs:61:2)`
`    at async file:///home/androtim/brainrot.js/generate/localBuild.mjs:88:2 {`
`  code: 'ECONNREFUSED',`
`  errno: -111,`
`  sql: undefined,`
`  sqlState: undefined,`
`  sqlMessage: undefined`
`}`

Does it mean that the port is not open?
I do not understand what is happening.

Note: I am running on an i3 on Linux Ubuntu 23.10

**Comment by noahgsolomon** [comment]
3306 is the port the database is using. 

if (!local) {
		await query(
			"UPDATE `pending-videos` SET status = 'Transcribing audio.mp3', progress = 20 WHERE video_id = ?",
			[videoId]
		);
	}


Do you see all these blocks? If you're getting this error it likely means local is false or not defined in a file. Delete all these blocks and remove query import in these files.

Let me know if this fixes the problem!

**Comment by noahgsolomon** [comment]
or pull the recent change to the repository i just made. It should fix the problem

**Comment by Androtim** [comment]
ok thanks I did a full reinstall and i'll see if it works now!

**Comment by Androtim** [comment]
ok thank you everything is working now! However, I am running into another issue that I cannot resolve. should I continue in this thread of open another issue?
